name: "[TEST] actions"
env:
  IMAGE_TAG: ${{ github.sha }}

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v4
    - name: Checking...
      run: |
        echo "Deploying to the environment: ${{ github.ref_name }}"
        echo "A: $GITHUB_SHA"
        echo "Deploying tag: ${IMAGE_TAG}"
        echo "Secret value: ${{ secrets.NAM }}"
        echo "Variable value: ${{ vars.VAR }}"
