name: "[TEST] actions"
env:
  IMAGE_TAG: ${{ github.sha }}

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    - name: Checking...
      run: |
        docker --version
        docker compose version || echo "docker compose not found"
        docker-compose --version || echo "docker-compose not found"
      
        for i in {1..5}
        do
          if [ -d "/webroot" ]; then
            echo "🔁 Looping number $i"
          else
            echo "fail"
          fi
        done
        
        echo "Deploying to the environment: ${{ github.ref_name }}"
        echo "A: $GITHUB_SHA"
        echo "Deploying tag: ${IMAGE_TAG}"
        echo "Secret value: ${{ secrets.NAM }}"
        echo "Variable value: ${{ vars.VAR }}"
