name: Test Github Environments

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
    - uses: actions/checkout@v4
    - name: Checking...
      run: |
        echo "Deploying to the environment: ${{ github.ref_name }}"
        echo "Secret value: ${{ secrets.NAM }}"
